// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: router/allowed_source_domain_sender.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// @param domain_id
// @param address
type AllowedSourceDomainSender struct {
	DomainId uint32 `protobuf:"varint,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Address  []byte `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *AllowedSourceDomainSender) Reset()         { *m = AllowedSourceDomainSender{} }
func (m *AllowedSourceDomainSender) String() string { return proto.CompactTextString(m) }
func (*AllowedSourceDomainSender) ProtoMessage()    {}
func (*AllowedSourceDomainSender) Descriptor() ([]byte, []int) {
	return fileDescriptor_665d23dfeebb8ee5, []int{0}
}
func (m *AllowedSourceDomainSender) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AllowedSourceDomainSender) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AllowedSourceDomainSender.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AllowedSourceDomainSender) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowedSourceDomainSender.Merge(m, src)
}
func (m *AllowedSourceDomainSender) XXX_Size() int {
	return m.Size()
}
func (m *AllowedSourceDomainSender) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowedSourceDomainSender.DiscardUnknown(m)
}

var xxx_messageInfo_AllowedSourceDomainSender proto.InternalMessageInfo

func (m *AllowedSourceDomainSender) GetDomainId() uint32 {
	if m != nil {
		return m.DomainId
	}
	return 0
}

func (m *AllowedSourceDomainSender) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func init() {
	proto.RegisterType((*AllowedSourceDomainSender)(nil), "noble.router.AllowedSourceDomainSender")
}

func init() {
	proto.RegisterFile("router/allowed_source_domain_sender.proto", fileDescriptor_665d23dfeebb8ee5)
}

var fileDescriptor_665d23dfeebb8ee5 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2c, 0xca, 0x2f, 0x2d,
	0x49, 0x2d, 0xd2, 0x4f, 0xcc, 0xc9, 0xc9, 0x2f, 0x4f, 0x4d, 0x89, 0x2f, 0xce, 0x2f, 0x2d, 0x4a,
	0x4e, 0x8d, 0x4f, 0xc9, 0xcf, 0x4d, 0xcc, 0xcc, 0x8b, 0x2f, 0x4e, 0xcd, 0x4b, 0x49, 0x2d, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc9, 0xcb, 0x4f, 0xca, 0x49, 0xd5, 0x83, 0x68, 0x50,
	0x0a, 0xe2, 0x92, 0x74, 0x84, 0xe8, 0x09, 0x06, 0x6b, 0x71, 0x01, 0xeb, 0x08, 0x06, 0x6b, 0x10,
	0x92, 0xe6, 0xe2, 0x84, 0x9a, 0x90, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1b, 0xc4, 0x01,
	0x11, 0xf0, 0x4c, 0x11, 0x92, 0xe0, 0x62, 0x4f, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0x96, 0x60,
	0x52, 0x60, 0xd4, 0xe0, 0x09, 0x82, 0x71, 0x9d, 0xc2, 0x4f, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48,
	0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1,
	0x58, 0x8e, 0x21, 0xca, 0x36, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x3f,
	0x39, 0xb3, 0x28, 0x39, 0x27, 0x35, 0x2d, 0x33, 0x4f, 0x1f, 0xec, 0x20, 0xdd, 0xe4, 0xe4, 0x92,
	0x02, 0xdd, 0x82, 0xa2, 0xcc, 0xb2, 0xc4, 0x92, 0x54, 0xdd, 0xa4, 0xd2, 0xcc, 0x9c, 0x94, 0x62,
	0xfd, 0x0a, 0x7d, 0xa8, 0xbf, 0x4a, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0x3e, 0x30, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x04, 0x3f, 0x65, 0xee, 0x00, 0x00, 0x00,
}

func (m *AllowedSourceDomainSender) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AllowedSourceDomainSender) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllowedSourceDomainSender) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintAllowedSourceDomainSender(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.DomainId != 0 {
		i = encodeVarintAllowedSourceDomainSender(dAtA, i, uint64(m.DomainId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAllowedSourceDomainSender(dAtA []byte, offset int, v uint64) int {
	offset -= sovAllowedSourceDomainSender(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AllowedSourceDomainSender) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DomainId != 0 {
		n += 1 + sovAllowedSourceDomainSender(uint64(m.DomainId))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovAllowedSourceDomainSender(uint64(l))
	}
	return n
}

func sovAllowedSourceDomainSender(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAllowedSourceDomainSender(x uint64) (n int) {
	return sovAllowedSourceDomainSender(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AllowedSourceDomainSender) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAllowedSourceDomainSender
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AllowedSourceDomainSender: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AllowedSourceDomainSender: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainId", wireType)
			}
			m.DomainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllowedSourceDomainSender
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DomainId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAllowedSourceDomainSender
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAllowedSourceDomainSender
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAllowedSourceDomainSender
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = append(m.Address[:0], dAtA[iNdEx:postIndex]...)
			if m.Address == nil {
				m.Address = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAllowedSourceDomainSender(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAllowedSourceDomainSender
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAllowedSourceDomainSender(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAllowedSourceDomainSender
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAllowedSourceDomainSender
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAllowedSourceDomainSender
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAllowedSourceDomainSender
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAllowedSourceDomainSender
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAllowedSourceDomainSender
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAllowedSourceDomainSender        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAllowedSourceDomainSender          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAllowedSourceDomainSender = fmt.Errorf("proto: unexpected end of group")
)
