// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: router/mint.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// mints are stored so incoming IBC forward messages can check if a mint has been processed
// @param amount
// @param destinationDomain
// @param mintRecipient
type Mint struct {
	SourceDomainSender string      `protobuf:"bytes,1,opt,name=source_domain_sender,json=sourceDomainSender,proto3" json:"source_domain_sender,omitempty"`
	Nonce              uint64      `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Amount             *types.Coin `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	DestinationDomain  string      `protobuf:"bytes,4,opt,name=destination_domain,json=destinationDomain,proto3" json:"destination_domain,omitempty"`
	MintRecipient      string      `protobuf:"bytes,5,opt,name=mint_recipient,json=mintRecipient,proto3" json:"mint_recipient,omitempty"`
}

func (m *Mint) Reset()         { *m = Mint{} }
func (m *Mint) String() string { return proto.CompactTextString(m) }
func (*Mint) ProtoMessage()    {}
func (*Mint) Descriptor() ([]byte, []int) {
	return fileDescriptor_650d9754adf300ce, []int{0}
}
func (m *Mint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Mint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Mint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Mint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mint.Merge(m, src)
}
func (m *Mint) XXX_Size() int {
	return m.Size()
}
func (m *Mint) XXX_DiscardUnknown() {
	xxx_messageInfo_Mint.DiscardUnknown(m)
}

var xxx_messageInfo_Mint proto.InternalMessageInfo

func (m *Mint) GetSourceDomainSender() string {
	if m != nil {
		return m.SourceDomainSender
	}
	return ""
}

func (m *Mint) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Mint) GetAmount() *types.Coin {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Mint) GetDestinationDomain() string {
	if m != nil {
		return m.DestinationDomain
	}
	return ""
}

func (m *Mint) GetMintRecipient() string {
	if m != nil {
		return m.MintRecipient
	}
	return ""
}

func init() {
	proto.RegisterType((*Mint)(nil), "noble.router.Mint")
}

func init() { proto.RegisterFile("router/mint.proto", fileDescriptor_650d9754adf300ce) }

var fileDescriptor_650d9754adf300ce = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x3f, 0x4b, 0x03, 0x41,
	0x10, 0xc5, 0xb3, 0x9a, 0x04, 0x5c, 0xff, 0x40, 0x96, 0x14, 0x67, 0x8a, 0x25, 0x08, 0x42, 0x9a,
	0xec, 0x1a, 0x2d, 0xed, 0xd4, 0xd6, 0xe6, 0xc4, 0xc6, 0x26, 0xdc, 0x5d, 0x86, 0x73, 0x21, 0x37,
	0x13, 0x76, 0xf7, 0x82, 0x7e, 0x0b, 0x3f, 0x96, 0x65, 0x3a, 0x2d, 0x25, 0xf7, 0x45, 0xe4, 0x76,
	0x4f, 0xb0, 0x9b, 0x79, 0xbf, 0x07, 0xef, 0xf1, 0xf8, 0xc8, 0x52, 0xed, 0xc1, 0xea, 0xca, 0xa0,
	0x57, 0x1b, 0x4b, 0x9e, 0xc4, 0x09, 0x52, 0xbe, 0x06, 0x15, 0xc1, 0x44, 0x16, 0xe4, 0x2a, 0x72,
	0x3a, 0xcf, 0x1c, 0xe8, 0xed, 0x22, 0x07, 0x9f, 0x2d, 0x74, 0x41, 0x06, 0xa3, 0x7b, 0x32, 0x2e,
	0xa9, 0xa4, 0x70, 0xea, 0xf6, 0x8a, 0xea, 0xc5, 0x17, 0xe3, 0xfd, 0x47, 0x83, 0x5e, 0x5c, 0xf1,
	0xb1, 0xa3, 0xda, 0x16, 0xb0, 0x5c, 0x51, 0x95, 0x19, 0x5c, 0x3a, 0xc0, 0x15, 0xd8, 0x84, 0x4d,
	0xd9, 0xec, 0x28, 0x15, 0x91, 0x3d, 0x04, 0xf4, 0x14, 0x88, 0x18, 0xf3, 0x01, 0x12, 0x16, 0x90,
	0x1c, 0x4c, 0xd9, 0xac, 0x9f, 0xc6, 0x47, 0x2c, 0xf8, 0x30, 0xab, 0xa8, 0x46, 0x9f, 0x1c, 0x4e,
	0xd9, 0xec, 0xf8, 0xfa, 0x5c, 0xc5, 0x5e, 0xaa, 0xed, 0xa5, 0xba, 0x5e, 0xea, 0x9e, 0x0c, 0xa6,
	0x9d, 0x51, 0xcc, 0xb9, 0x58, 0x81, 0xf3, 0x06, 0x33, 0x6f, 0x08, 0xbb, 0xfc, 0xa4, 0x1f, 0x82,
	0x47, 0xff, 0x48, 0x4c, 0x17, 0x97, 0xfc, 0xac, 0x1d, 0x61, 0x69, 0xa1, 0x30, 0x1b, 0x03, 0xe8,
	0x93, 0x41, 0xb0, 0x9e, 0xb6, 0x6a, 0xfa, 0x27, 0xde, 0x3d, 0x7f, 0xee, 0x25, 0xdb, 0xed, 0x25,
	0xfb, 0xd9, 0x4b, 0xf6, 0xd1, 0xc8, 0xde, 0xae, 0x91, 0xbd, 0xef, 0x46, 0xf6, 0x5e, 0x6e, 0x4b,
	0xe3, 0x5f, 0xeb, 0x5c, 0x15, 0x54, 0x69, 0xe7, 0x6d, 0x86, 0x25, 0xac, 0x69, 0x0b, 0xf3, 0x2d,
	0xa0, 0xaf, 0x2d, 0x38, 0x1d, 0x76, 0x9d, 0x77, 0x83, 0xbf, 0xe9, 0xee, 0xf0, 0xef, 0x1b, 0x70,
	0xf9, 0x30, 0xec, 0x76, 0xf3, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xda, 0xea, 0xd5, 0xbb, 0x90, 0x01,
	0x00, 0x00,
}

func (m *Mint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Mint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Mint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MintRecipient) > 0 {
		i -= len(m.MintRecipient)
		copy(dAtA[i:], m.MintRecipient)
		i = encodeVarintMint(dAtA, i, uint64(len(m.MintRecipient)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.DestinationDomain) > 0 {
		i -= len(m.DestinationDomain)
		copy(dAtA[i:], m.DestinationDomain)
		i = encodeVarintMint(dAtA, i, uint64(len(m.DestinationDomain)))
		i--
		dAtA[i] = 0x22
	}
	if m.Amount != nil {
		{
			size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Nonce != 0 {
		i = encodeVarintMint(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x10
	}
	if len(m.SourceDomainSender) > 0 {
		i -= len(m.SourceDomainSender)
		copy(dAtA[i:], m.SourceDomainSender)
		i = encodeVarintMint(dAtA, i, uint64(len(m.SourceDomainSender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMint(dAtA []byte, offset int, v uint64) int {
	offset -= sovMint(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Mint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SourceDomainSender)
	if l > 0 {
		n += 1 + l + sovMint(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovMint(uint64(m.Nonce))
	}
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovMint(uint64(l))
	}
	l = len(m.DestinationDomain)
	if l > 0 {
		n += 1 + l + sovMint(uint64(l))
	}
	l = len(m.MintRecipient)
	if l > 0 {
		n += 1 + l + sovMint(uint64(l))
	}
	return n
}

func sovMint(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMint(x uint64) (n int) {
	return sovMint(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Mint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMint
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Mint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Mint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceDomainSender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceDomainSender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMint
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Amount == nil {
				m.Amount = &types.Coin{}
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationDomain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationDomain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintRecipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMint
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMint
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMint
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintRecipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMint(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMint
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMint(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMint
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMint
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMint
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMint
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMint
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMint        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMint          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMint = fmt.Errorf("proto: unexpected end of group")
)
